# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWebEngineWidgets import QWebEngineView
import io
import sys
from typing import Tuple, List, Union
from folium.plugins import MarkerCluster
from folium.map import Marker
import folium
import pandas as pd
from .analytics.tools import Analytics

class Ui_MainWindow(object):

    def resetMap(self, markers: List[Union[Marker, MarkerCluster]]=None):
        markers = markers if markers is not None else []
        map = folium.Map(location=[50.2577, 14.9939], tiles='Stamen Terrain', zoom_start = 5)
        print(len(markers))
        for i, marker in enumerate(markers):
            marker.add_to(map)
            if i == 60:
                break
        data = io.BytesIO()
        map.save(data, close_file=False)

        self.map_layer.setHtml(data.getvalue().decode())


        data.close()

    def __init__(self, MainWindow, data: pd.DataFrame = None):
        self._translate = QtCore.QCoreApplication.translate

        self.data = data

        self.setupUi(MainWindow)
        markers = Analytics.getMarkers(data)
        self.resetMap(markers)
        self.setupFunctional()
        
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1400, 800)


        # Init Central Window
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_central_vidget = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_central_vidget.setObjectName("gridLayout_central_vidget")

        # Init Tab Widget on Central Window
        self.tab_widget = QtWidgets.QTabWidget(self.centralwidget)
        self.tab_widget.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.tab_widget.setObjectName("tab_widget")


        ### Map Tab ###
        self.map_tab = QtWidgets.QWidget()
        self.map_tab.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.map_tab.setObjectName("map_tab")
        self.gridLayout_map_tab = QtWidgets.QGridLayout(self.map_tab)
        self.gridLayout_map_tab.setObjectName("gridLayout_map_tab")
        
        # Map Layer (Map Tab)
        self.map_layer = QWebEngineView()
        self.map_layer.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.map_layer.sizePolicy().hasHeightForWidth())
        self.map_layer.setSizePolicy(sizePolicy)
        self.map_layer.setStyleSheet("")
        self.map_layer.setObjectName("map_layer")
        self.gridLayout_map_layer = QtWidgets.QGridLayout(self.map_layer)
        self.gridLayout_map_layer.setObjectName("gridLayout_map_layer")


        # Filter Layer (Map Tab)
        self.settings_layer = QtWidgets.QWidget()
        self.settings_layer.setStyleSheet("")
        self.settings_layer.setObjectName("settings_layer")
        self.gridLayout_settings_layer = QtWidgets.QGridLayout(self.settings_layer)
        self.gridLayout_settings_layer.setObjectName("gridLayout_settings_layer")

        self.pushButton_settings_close = QtWidgets.QPushButton(self.settings_layer)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_settings_close.setFont(font)
        self.pushButton_settings_close.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_settings_close.setStyleSheet("background-color: rgb(85, 85, 85);\ncolor: rgb(255, 255, 255);")
        self.pushButton_settings_close.setObjectName("pushButton_settings_close")
        self.pushButton_settings_close.setText(self._translate("MainWindow", "Close"))
        self.gridLayout_settings_layer.addWidget(self.pushButton_settings_close, 0, 0, 1, 1, QtCore.Qt.AlignRight)
        
        self.settings_label_keyWords = QtWidgets.QLabel(self.settings_layer)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.settings_label_keyWords.setFont(font)
        self.settings_label_keyWords.setObjectName("settings_label_keyWords")
        self.settings_label_keyWords.setText(self._translate("MainWindow", "Key Words"))
        self.gridLayout_settings_layer.addWidget(self.settings_label_keyWords, 1, 0, 1, 1)
        
        
        self.plainTextEdit_settings_keyWords = QtWidgets.QPlainTextEdit(self.settings_layer)
        self.plainTextEdit_settings_keyWords.setStyleSheet("font: 10pt \"JetBrains Mono\";")
        self.plainTextEdit_settings_keyWords.setObjectName("plainTextEdit_settings_keyWords")
        self.gridLayout_settings_layer.addWidget(self.plainTextEdit_settings_keyWords, 2, 0, 1, 1)
        
        self.label_settings_timeFrom = QtWidgets.QLabel(self.settings_layer)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_settings_timeFrom.setFont(font)
        self.label_settings_timeFrom.setObjectName("label_settings_timeFrom")
        self.label_settings_timeFrom.setText(self._translate("MainWindow", "Time From:"))
        self.gridLayout_settings_layer.addWidget(self.label_settings_timeFrom, 3, 0, 1, 1)

        self.date_from = QtWidgets.QDateEdit(self.settings_layer)
        self.date_from.setObjectName("date_from")
        self.date_from.setDate(QtCore.QDate(2020,1,1))
        self.gridLayout_settings_layer.addWidget(self.date_from, 4, 0, 1, 1)

        self.label_settings_timeTo = QtWidgets.QLabel(self.settings_layer)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_settings_timeTo.setFont(font)
        self.label_settings_timeTo.setObjectName("label_settings_timeTo")
        self.label_settings_timeTo.setText(self._translate("MainWindow", "Time To"))
        self.gridLayout_settings_layer.addWidget(self.label_settings_timeTo, 5, 0, 1, 1)
        
        self.date_to = QtWidgets.QDateEdit(self.settings_layer)
        self.date_to.setObjectName("date_to")
        self.date_to.setDate(QtCore.QDate(2022, 1, 1))
        self.gridLayout_settings_layer.addWidget(self.date_to, 6, 0, 1, 1)
        
        self.pushButton_settings_apply = QtWidgets.QPushButton(self.settings_layer)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_settings_apply.setFont(font)
        self.pushButton_settings_apply.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_settings_apply.setStyleSheet("background-color: rgb(76, 175, 80);\ncolor: rgb(255, 255, 255);")
        self.pushButton_settings_apply.setObjectName("pushButton_settings_apply")
        self.pushButton_settings_apply.setText(self._translate("MainWindow", "Apply"))
        self.gridLayout_settings_layer.addWidget(self.pushButton_settings_apply, 7, 0, 1, 1)
        
        
        # Create Stacked Widget on Map Tab (for Map and Filter Layer)
        self.stackedWidget_map_tab = QtWidgets.QStackedWidget(self.map_tab)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.stackedWidget_map_tab.setFont(font)
        self.stackedWidget_map_tab.setObjectName("stackedWidget_map_tab")
        # Add Layers (Map, Filter) to Stacked  Widget
        self.stackedWidget_map_tab.addWidget(self.settings_layer)
        self.stackedWidget_map_tab.addWidget(self.map_layer)

        self.gridLayout_map_tab.addWidget(self.stackedWidget_map_tab, 0, 0, 1, 1)
        
        
        ### Projects Tab ###
        self.projects_tab = QtWidgets.QWidget()
        self.projects_tab.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.projects_tab.setObjectName("projects_tab")
        self.gridLayout_progects_tab = QtWidgets.QGridLayout(self.projects_tab)
        self.gridLayout_progects_tab.setObjectName("gridLayout_progects_tab")

        self.pushButton_current_projects_save = QtWidgets.QPushButton(self.projects_tab)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_current_projects_save.setFont(font)
        self.pushButton_current_projects_save.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_current_projects_save.setObjectName("pushButton_current_projects_save")
        self.pushButton_current_projects_save.setText(self._translate("MainWindow", "Save Current List"))
        self.gridLayout_progects_tab.addWidget(self.pushButton_current_projects_save, 0, 0, 1, 1)

        self.projects_table = QtWidgets.QTreeWidget(self.projects_tab)
        self.projects_table.setObjectName("projects_table")
        item_0 = QtWidgets.QTreeWidgetItem(self.projects_table)
        self.gridLayout_progects_tab.addWidget(self.projects_table, 1, 0, 1, 1)

        # Add both tabs (Map, Projects) to Tabs Widget
        self.tab_widget.addTab(self.map_tab, "")
        self.tab_widget.addTab(self.projects_tab, "")
        
        self.gridLayout_central_vidget.addWidget(self.tab_widget, 0, 0, 1, 1)

        MainWindow.setCentralWidget(self.centralwidget)


        ### Menu
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionFilter = QtWidgets.QAction(MainWindow)
        self.actionFilter.setObjectName("actionFilter")
        self.menuFile.addAction(self.actionFilter)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tab_widget.setCurrentIndex(0)
        self.stackedWidget_map_tab.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(self._translate("MainWindow", "WorkCapms Helper"))


        # Projects Table
        self.projects_table.headerItem().setText(0, self._translate("MainWindow", "Code"))
        self.projects_table.headerItem().setText(1, self._translate("MainWindow", "Name"))
        self.projects_table.headerItem().setText(2, self._translate("MainWindow", "Date"))
        self.projects_table.headerItem().setText(3, self._translate("MainWindow", "Country"))
        self.projects_table.headerItem().setText(4, self._translate("MainWindow", "Keywords"))
        self.projects_table.headerItem().setText(5, self._translate("MainWindow", "Link"))
        __sortingEnabled = self.projects_table.isSortingEnabled()
        self.projects_table.setSortingEnabled(False)
        self.projects_table.topLevelItem(0).setText(0, self._translate("MainWindow", "J78"))
        self.projects_table.topLevelItem(0).setText(1, self._translate("MainWindow", "Young"))
        self.projects_table.topLevelItem(0).setText(2, self._translate("MainWindow", "10.10.10-20.20.20"))
        self.projects_table.topLevelItem(0).setText(3, self._translate("MainWindow", "France"))
        self.projects_table.topLevelItem(0).setText(4, self._translate("MainWindow", "#Tents"))
        self.projects_table.topLevelItem(0).setText(5, self._translate("MainWindow", "www.yandex.ru"))
        self.projects_table.setSortingEnabled(__sortingEnabled)
        
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.map_tab), self._translate("MainWindow", "Map"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.projects_tab), self._translate("MainWindow", "Projects List"))
        
        self.menuFile.setTitle(self._translate("MainWindow", "File"))
        self.actionFilter.setText(self._translate("MainWindow", "Open Filter"))

    def setupFunctional(self):
        self.pushButton_settings_close.clicked.connect(lambda : self._change_state_map_tab_settings(close=True))
        self.actionFilter.triggered.connect(self._change_state_map_tab_settings)

        self.pushButton_settings_apply.clicked.connect(self._apply_settings)

    def _apply_settings(self):
        key_words_content = self.plainTextEdit_settings_keyWords.toPlainText()
        key_words = key_words_content.split('|')
        key_words = [w.strip() for w in key_words]
        date_from = self.date_from.date().toString('dd-MM-yyyy')
        date_to = self.date_from.date().toString('dd-MM-yyyy')

        df = Analytics.selectByTime(self.data, date_from, date_to)
        df , keywords_list_found = Analytics.selectByKeywords(df, key_words)

        markers = Analytics.getMarkers(df, keywords_list_found)
        self.resetMap(markers)


    
    def _change_state_map_tab_settings(self, close: bool):
        idx = 1 if close else 0
        self.stackedWidget_map_tab.setCurrentIndex(idx)

if __name__ == "__main__":
    df = pd.read_csv("data/new_data.csv")
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow(MainWindow, df)

    MainWindow.show()
    sys.exit(app.exec_())
